services:
  - type: web
    name: devopsfinal
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn lostandfound_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: devopsfinal-db
          property: connectionString
      - key: MEDIA_ROOT
        value: /var/data/media
    disks:
      - name: media
        mountPath: /var/data/media
        sizeGB: 1

databases:
  - name: devopsfinal-db
    databaseName: devopsfinal
    user: devopsfinal
    plan: free
